 
upstream reprohum_reg_app {
    server web:5000;
}


#map $sent_http_content_type $expires {
#    application/javascript -1; # check 'mime.types' file for the proper value
#    default off;
#}

server {

    listen 80;

    location / {
        proxy_pass http://reprohum_reg_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

        location /static/ {
        #alias /home/app/web/project/static/;
        root /home/app/web/project;
        # 'Cache-Control: no-cache' header
        # will be added for javascript files only
        #expires $expires;
    }


#        location ~* \.js$ {
#            expires -1;
#    }



}
